when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  release-helper:
    image: woodpeckerci/plugin-ready-release-go:1.1.0
    pull: true
    secrets: [github_token]
    settings:
      forge_type: github
      git_email: github-bot@vmgware.dev
      github_token:
        from_secret: GITHUB_TOKEN
      release_branch: ${CI_REPO_DEFAULT_BRANCH}
