variables:
  - &buildx_plugin "docker.io/woodpeckerci/plugin-docker-buildx:3.0.1"
  - &platforms "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x"

  # vars used on push / tag events only
  - publish_logins: &publish_logins # Default DockerHub login
      - registry: https://index.docker.io/v1/
        username: "vmgware"
        password:
          from_secret: docker_password
      - registry: https://harbor.vmgware.dev
        username: "robot$vmgware"
        password:
          from_secret: harbor_password
  - &publish_repos "vmgware/woodpecker-plugin-caprover-deploy,harbor.vmgware.dev/woodpecker/plugin-caprover-deploy"

steps:
  dryrun:
    image: *buildx_plugin
    settings:
      dockerfile: Dockerfile
      dry_run: true
      repo: woodpeckerci/plugin-ready-release-go
      platforms: *platforms
      tag: test
    when:
      event: pull_request

  publish-next:
    image: *buildx_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile
      platforms: *platforms
      tag: next
      logins: *publish_logins
    when:
      branch: main
      event: push

  publish-tag:
    image: *buildx_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile
      platforms: *platforms
      tag: [latest, "${CI_COMMIT_TAG}"]
      logins: *publish_logins
    when:
      event: tag
